-- Add more diverse exercises
INSERT INTO public.exercises (name, description, xp_per_set) VALUES
  ('Bicep Curls', 'Isolation exercise for biceps', 8),
  ('Tricep Dips', 'Bodyweight tricep exercise', 10),
  ('Leg Press', 'Machine-based lower body exercise', 8),
  ('Shoulder Shrugs', 'Trapezius strengthening exercise', 6),
  ('Calf Raises', 'Lower leg isolation exercise', 5),
  ('Hammer Curls', 'Bicep and forearm exercise', 8),
  ('Lateral Raises', 'Shoulder isolation exercise', 7),
  ('Front Raises', 'Anterior deltoid exercise', 7),
  ('Face Pulls', 'Rear deltoid and upper back exercise', 8),
  ('Romanian Deadlift', 'Hamstring focused exercise', 10),
  ('Bulgarian Split Squat', 'Single leg strength exercise', 12),
  ('Hip Thrusts', 'Glute strengthening exercise', 10),
  ('Cable Rows', 'Back and bicep exercise', 8),
  ('Lat Pulldown', 'Back width exercise', 8),
  ('Chest Flyes', 'Chest isolation exercise', 7),
  ('Incline Bench Press', 'Upper chest exercise', 9),
  ('Decline Bench Press', 'Lower chest exercise', 9),
  ('Dumbbell Press', 'Shoulder and chest exercise', 8),
  ('Arnold Press', 'Complete shoulder development', 10),
  ('Upright Rows', 'Shoulder and trap exercise', 7),
  ('Box Jumps', 'Explosive lower body exercise', 15),
  ('Wall Balls', 'Full body functional exercise', 12),
  ('Kettlebell Swings', 'Hip hinge power exercise', 12),
  ('Battle Ropes', 'Full body cardio exercise', 18),
  ('Farmer Carry', 'Grip and core strength', 10),
  ('Sled Push', 'Lower body power exercise', 15),
  ('Tire Flips', 'Full body strength exercise', 20),
  ('Medicine Ball Slams', 'Core and power exercise', 12),
  ('Jump Rope', 'Cardio and coordination', 8),
  ('High Knees', 'Cardio exercise', 8),
  ('Butt Kicks', 'Cardio warm-up exercise', 6),
  ('Side Plank', 'Oblique strengthening', 12),
  ('Russian Twists', 'Core rotation exercise', 10),
  ('Bicycle Crunches', 'Abdominal exercise', 8),
  ('Leg Raises', 'Lower ab exercise', 10),
  ('Hanging Knee Raises', 'Advanced core exercise', 15),
  ('Dragon Flags', 'Elite core exercise', 25),
  ('Handstand Push-ups', 'Advanced shoulder exercise', 20),
  ('Muscle-ups', 'Advanced pull and push exercise', 30),
  ('Pistol Squats', 'Single leg strength exercise', 18)
ON CONFLICT DO NOTHING;